config/routes.rb
Rails.application.routes.draw do	
  root to: 'visitors#index'


  # user routes
  get '/u/:id' => 'users#show'
  resources :users
  # string -- user.email.split("@")[0]


  # session routes
  get '/login' => 'users#login'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # campaign routes
  get '/c/index' => 'campaigns#index', as: :index_campaign
  get '/c/create' => 'campaigns#campaign_creation', as: :create_campaign
  post '/c/create' => 'campaigns#show'
  get '/c/:title' => 'campaigns#show', as: :show_campaign
  resources :campaigns
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	validates_uniqueness_of :title

	
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

  def self.koala(auth)
  	token = auth[:token]
  	facebook = Koala::Facebook::API.new(token)
  	facebook.get_object("me?fields=picture")
  end

  def add_projects(campaign)
    '''runs after campaign is created'''
    campaign.ownership = self.id
    self.projects_owned.push(campaign.id)  
  end

  def get_projects
    return self.projects.split(',')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  #helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end
=begin
    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end
=end
    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/campaigns_controller.rb
require 'open-uri'
class CampaignsController < ApplicationController

	def campaign_creation
		@campaign = Campaign.new
	end

	def create
		@campaign = Campaign.new(campaign_params)
		@campain.ownership = current_user.id
		current_user.add_project(@campaign)
		@campaign.save

		# dealing with cover image
		upload_path = Rails.root.join("app","assets","images","cover_images")
		image_name =  params[:campaign][:cover_image].original_filename
		File.open(upload_path + image_name, 'wb') do |f|
			f.write(params[:campaign][:cover_image].read)
		end
		#this is stupid notation, should be changed, but for some reason adding the strings kept adding an unnecessary "/" and broke the thing
		File.rename(upload_path.join(image_name), upload_path + "#{Campaign.find_by_title(params[:campaign][:title]).id.to_s}#{File.extname(image_name)}")

		redirect_to "/c/#{@campaign.title}"
	end

	def show
		@campaign = Campaign.find_by_title(params[:title])
		@campaign.views += 1
		#@current_bitcoin_price = JSON.parse(open('https://api.coindesk.com/v1/bpi/currentprice.json').read)['bpi']['USD']['rate'].to_f.round(2)
		# potentially could make it unique to each session
		@campaign.save
	end

	def index
		@campaigns = Campaign.all
	end
	private
		def campaign_params
			#missing: uploaded_qr_code, tags
			#tags to come when dynamically searching for keywords
			params.require(:campaign).permit(:title,:type,:preferred_currency, :category,:qr_code, :goal, :description, :website)
    	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    session[:auth_token] = auth.access_token
    redirect_to '/', :notice => 'Signed in!'
    #redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!
  #before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def login
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		@campaigns = Campaign.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign_form.html.erb
<style>
	#pref-coin{
		font-weight: bold;
	}
</style>
<h1> Campaign creation form </h1>
<div class = "container" style = "width: 600px;box-shadow: 0 0 2px black; margin-bottom: 50px;">
<fieldset>
	<legend>Campaign</legend>

<%= form_for @campaign, :html => { :class => "form-horizontal form-group"} do |f| %>
	<div class = 'col-md-12 col-md-offset-2' style ='margin-top:5px; overflow: auto; display: inline-block;border:4px; align:left;'>
					
		Title<span style = "color:red;">*</span><br/> <%= f.text_field :title, :required => true, :placeholder => "Name of your project" %><br>
		
		<div class ="row top-buffer">
			Category<br/> <%= f.select :category, ["Uncategorized", "People", "Events", "Non-profit Organizations", "Websites and Blogs", "Software", "Businesses", "Media and Content Creation", "Authors", "Singers", "Other"]%>
		</div>

		<div class = "row top-buffer">
			Preferred Currency<br/> <%= f.select :preferred_currency, ["Bitcoin", "Dogecoin"] %>
		</div>

		<div class = "row top-buffer">
			<span id ="pref-coin">Bitcoin</span> wallet address<span style = "color:red;">*</span><br/><%= f.text_field :qr_code, :required => true%>
		</div>
		<div class = 'row top-buffer'>
			<%= f.file_field :uploaded_qr_code, :text => "Upload QR Code", :required => true %>
		</div>

		<div class = 'row top-buffer'>
			Goal<br/><%= f.text_field :goal, :enabled => true%> or <%= f.check_box :goal, :onclick => "changeElement()" %> Open Donations
		</div>
		<script>
			//select B and D and L or whatever from unicode
			document.getElementById("campaign_preferred_currency").onchange = function(){
				document.getElementById("pref-coin-initial").innerHTML = this.options[this.selectedIndex].text[0];	
				document.getElementById("pref-coin").innerHTML = this.options[this.selectedIndex].text;
			}
			var elementCheckMark = document.getElementById("campaign_open_donations")
			var outputField = document.getElementById("campaign_goal")
			function changeElement() {
				if (elementCheckMark.checked === true){
					
					outputField.disabled = true
					outputField.value = "Open Donations"
				}	
				else{
					outputField.disabled = false
					outputField.value = ""
				}
			}

		</script>

		<div class = 'row top-buffer'>
			Description<span style = "color:red;">*</span><br/> <%= f.text_area :description, :required => true, :rows=>'5', :cols=> "40", :style => "margin-bottom: 10px; resize: none;" %><br>
		</div>
		<!-- javascript here to generate a default suggestion description using title, category, preferred currency-->

		<div class = 'row top-buffer'>
			Cover Image<%= f.file_field :cover_image, :text => "Upload Cover Image", :class => "btn btn-sm btn-alert"%>
		</div>

	<%= f.submit "Save Campaign", :class => "btn btn-lg btn-primary top-buffer", :style => 'margin-bottom: 20px;' %>
	</div>
<% end %>
</fieldset>
</div>

app/views/campaigns/_form.html.erb
<style>
	#pref-coin{
		font-weight: bold;
	}
	#required{
		color:red;
	}
</style>


<legend>Submit a new Project </legend>
<div class = "container" style = "width: 600px; margin-bottom: 50px;">

<%= form_for @campaign do |f| %>
	<div class = 'col-md-offset-2' style ='margin-top:5px; align:left;'>
		<div class = "row top-buffer">		
		Title<span id = "required">*</span><br/> <%= f.text_field :title, :required => true, :placeholder => "Name of your project" %><br>
		</div>
		<div class ="row top-buffer">
			Category<br/> <%= f.select :category, ["Uncategorized", "People", "Events", "Non-profit Organizations", "Websites and Blogs", "Software", "Businesses", "Media and Content Creation", "Authors", "Singers", "Other"]%>
		</div>

		<div class = "row top-buffer">
			Preferred Currency<br/> <%= f.select :preferred_currency, ["Bitcoin", "Dogecoin"] %>
		</div>

		<div class = "row top-buffer">
			<span id ="pref-coin">Bitcoin</span> wallet address<span id = "required">*</span><br/><%= f.text_field :qr_code, :required => true%>
		</div>
		<div class = 'row top-buffer'>
			<%= f.file_field :uploaded_qr_code, :text => "Upload QR Code", :required => true %>
		</div>

		<div class = 'row top-buffer'>
			Goal<br/><%= f.text_field :goal, :enabled => true%> or <%= f.check_box :goal, :onclick => "changeElement()" %> Open Donations
		</div>
		<script>
			//select B and D and L or whatever from unicode
			document.getElementById("campaign_preferred_currency").onchange = function(){
				document.getElementById("pref-coin-initial").innerHTML = this.options[this.selectedIndex].text[0];	
				document.getElementById("pref-coin").innerHTML = this.options[this.selectedIndex].text;
			}
			function changeElement() {
				var elementCheckMark = document.getElementById("campaign_open_donations")
				var outputField = document.getElementById("campaign_goal")
				if (elementCheckMark.checked === true){
					
					outputField.disabled = true
					outputField.value = "Open Donations"
				}	
				else{
					outputField.disabled = false
					outputField.value = ""
				}
			}

		</script>

		<div class = 'row top-buffer'>
			Description<span id = "required">*</span><br/> <%= f.text_area :description, :required => true, :rows=>'5', :cols=> "40", :style => "margin-bottom: 10px; resize: none;" %><br>
		</div>
		<!-- javascript here to generate a default suggestion description using title, category, preferred currency-->

		<div class = 'row top-buffer'>
			Cover Image<%= f.file_field :cover_image, :text => "Upload Cover Image", :class => "btn btn-sm btn-alert"%>
		</div>

		<div class = 'row top-buffer'>
			Link to your website<%= f.text_field :website %>

	<%= f.submit "Save Campaign", :class => "btn btn-lg btn-primary top-buffer", :style => 'margin-bottom: 20px;' %>
	</div>
<% end %>

</div>

app/views/campaigns/_list.html.erb
<style>
	tr.row {
		border-bottom: 1px solid black;
		margin-top: 5px;
	}
	td#thumbnail{
		margin-top: 5px;
	}

	td#details {
		display:inline;
	}

	td#goal_zone {
		text-align:right;
	}
</style>

<table>
	<tbody>
		<% @campaigns.each do |c| %>
			<tr class = 'row border_bottom'>
				<td class = "thumbnail">
					<%= image_tag "cover_images/#{c.id}.png"%>
				</td>
				<td class = "details">
					<%= link_to c.title, show_campaign_path(c.title)%><br>
					Posted by:
				</td>
				<td class = "goal_zone">
					Goal:<%= c.goal %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/campaigns/_tags.html.erb
<style>
	li {
		display:inline;
	}
</style>

<!--
<% for tag in Campaign.find_by_title(params[:title].tags.split(",")) %>
	<li><%= button_to tag, '#' %></li>
<% end %>
-->

app/views/campaigns/campaign_creation.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
  <title>Submit a Campaign</title>
<style>
	.top-buffer{
		margin-top: 20px;

	}
	body{
		font-family: "open sans", sans-serif;
	}
</style>
</head>
<body>
	<%= render 'form'%>
</body>
<!--
<script type="text/javascript" src="grid.js"></script>
<script type="text/javascript" src="version.js"></script>
<script type="text/javascript" src="detector.js"></script>
<script type="text/javascript" src="formatinf.js"></script>
<script type="text/javascript" src="errorlevel.js"></script>
<script type="text/javascript" src="bitmat.js"></script>
<script type="text/javascript" src="datablock.js"></script>
<script type="text/javascript" src="bmparser.js"></script>
<script type="text/javascript" src="datamask.js"></script>
<script type="text/javascript" src="rsdecoder.js"></script>
<script type="text/javascript" src="gf256poly.js"></script>
<script type="text/javascript" src="gf256.js"></script>
<script type="text/javascript" src="decoder.js"></script>
<script type="text/javascript" src="qrcode.js"></script>
<script type="text/javascript" src="findpat.js"></script>
<script type="text/javascript" src="alignpat.js"></script>
<script type="text/javascript" src="databr.js"></script>
-->

app/views/campaigns/creation_callback.html.erb
<h1> Form works </h1>

<%= @campaign.title%>
<br>Accepts: <%= @campaign.preferred_currency %>

app/views/campaigns/index.html.erb
<legend> Campaigns </legend>

<%= link_to 'Create a campaign', create_campaign_path %>
<% begin %>
	<%= render "list" %>
<% rescue %>
	<% nil %>
<% end %>

app/views/campaigns/show.html.erb
<%= params[:title]%>

<br><br>
<div class = 'container' align = 'right'>
			
	<table class = 'table-striped table-bordered table-condensed table-responsive' style = "table-layout:auto;">
		<thead><th>Donation Info </th><th>Donation Info</th></thead>
			
			<tr><td class = "auto">Current Bitcoin exchange rate:</td><td><span id = "btc-rate"></span></td></tr>
			<tr><td>Accepts:</td><td> <%= @campaign.preferred_currency %></td></tr>
			<tr><td>Page views:</td><td> <%= @campaign.views%></td></tr>
			<tr><td>Address:</td><td><%=@campaign.qr_code%></td></tr>
			<tr><td><%= image_tag @campaign.location %></td></tr>

	</table>
</div>
<div class = 'container containter-fluid' style = "width: 600px; overflow: auto;box-shadow: 0 0 3px black;">
	<div class = "col-lg-10">
		<%= image_tag "cover_images/#{Campaign.find_by_title(params[:title]).id}.png" %>
		<%= @campaign.description  %>
		
	</div>
</div>

<script>
	$.get("https://api.coindesk.com/v1/bpi/currentprice.json", function( data ){
		$('btc-rate').text(data["bpi"]["USD"]["rate"])
	}, 'JSON');
</script>

app/views/layouts/_account_bar.html.erb
<div class = "navbar navbar-inverse navbar-fixed-top">
	<div class = "containter container-fluid">
	<% if current_user %>
		<li><%= link_to current_user.name, users_show_path, :style => "font-weight: bold;"%></li>
	<% else %>
		<li><%= link_to "Login", login_path %></li>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-inverse navbar-embossed" style= "background-color: #ecf0f1; border: 0px solid white; border-bottom:2px solid black; margin: 0px;" role= "navigation">
  <div class="container container-fluid">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left links">
        <%= render 'layouts/navigation_links' %>
        <!-- want no transition here -->
        <li><%= button_to "Post your Project", create_campaign_path, :method => :get, :class => "btn btn-md btn-block btn-success", :style => "margin-top: 8px;"%></li>

      </ul>
    </div>
  </div>



</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<style>
	li#elem{
    transition: background-color 0.5s ease;
  	}

  	li#elem:hover{
    background-color: #7f8c8d;
    }
</style>


<li><%= link_to image_tag("logo.gif"), root_url%></li>
<li id = 'elem'><%= link_to 'Home', root_url%></li>
<% if user_signed_in? %>
  <li id = 'elem'><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li id = 'elem'><%= link_to 'Sign in', login_path %></li>
<% end %>

  <li id = 'elem'><%= link_to 'Campaigns', index_campaign_path %></li>


<!-- Static pages, accounting for hidden directories -->
<% for static in Dir.entries(Rails.root.join("app", "views","pages")).map { |file_name| file_name.split(".")[0] }.compact %>
	<li id = 'elem'><%= link_to static.capitalize, page_path(static.downcase) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Littlebitback" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Littlebitback" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </head>
  <body>
    <header style= "margin:0px; padding:0px; border:0px">
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" style ="margin:0px; padding:0px; border:0px;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/blog.html.erb
<legend>Blog</legend>

app/views/pages/contact.html.erb
<legend>Contact Us</legend>

app/views/pages/faq.html.erb
<legend>Frequently asked questions</legend>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<!-- sign in form here -->



<!-- stylize these with :class => "css tags /descriptors" -->
<%= button_to "Login with Facebook", '/auth/facebook' %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<br><br>

<%= render "campaigns/list" %>

<!--
				~~~~Display~~~~

night mode 

higher - most valuable space
		- slideshow of the most popular
		- slide for the up-and-coming ~~~ define
			- each month, if there has been a spike in views, add it
		- new campaign gets showcased per certain number of unique inhits
			- cycles to a new campaign after 50 people have seen it on the front pages
		-track and document who gets the spots
		-facebook's like ~~ highfive limited to account ~ account security, capchta
			- list of campaigns you've highfived, bookmarked
			- twitter, facebook posts - popups, then remember whether or not to automatically tweet after vote -> not ever, maybe later, always


mid - bigger windows to click
	-infinite scroll
	-donate to all
	-donate to random
	-track and document who gets the spots
	-facebook's like
	- tag size

low - just random projects
	- option to sort all projects alphabetically
	- standard what's hot filter
		- more active projects towards the top
	- visual similar to reddit/voat
	- thumbnail

thumbnail - processing vs. gathering appropriate sizes straight from user
			-squarespace
			- kickstarter


frontpage - learns which categories user is interested in
		  - filters

HIGHFIVE - facebook like
			- able to be retracted
			- include image/video in the post


COMMENTS - be able to make comments on campaigns
			- threaded: comments on comments
				- high five on comments
			- ratings

show page - embedding youtube/vimeo links

imgur/youtube for hosting videos, pictures



		  -->